# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-03 10:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=60, unique=True)),
                ('password', models.CharField(max_length=12)),
                ('other_details', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('c_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('criteria', models.FloatField(blank=True, null=True)),
                ('salary', models.FloatField(blank=True, null=True)),
                ('back', models.CharField(blank=True, max_length=100, null=True)),
                ('ppt_date', models.DateTimeField(blank=True, null=True)),
                ('other_details', models.CharField(blank=True, max_length=1000, null=True)),
                ('reg_start', models.DateTimeField(blank=True, null=True)),
                ('reg_end', models.DateTimeField(blank=True, null=True)),
                ('reg_link', models.CharField(blank=True, max_length=1000, null=True)),
                ('placed_url', models.CharField(blank=True, max_length=500, null=True)),
                ('hired_people', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('msg_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=200)),
                ('message', models.CharField(default='', max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('r_id', models.AutoField(primary_key=True, serialize=False)),
                ('company', models.CharField(max_length=200)),
                ('shortlist', models.CharField(max_length=100)),
                ('filename', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=60, unique=True)),
                ('password', models.CharField(max_length=12)),
                ('phone', models.CharField(max_length=10)),
                ('gender', models.CharField(max_length=10)),
                ('roll', models.IntegerField()),
                ('branch', models.CharField(max_length=6)),
                ('ssc', models.FloatField()),
                ('hsc', models.FloatField()),
                ('average', models.FloatField()),
                ('placed', models.CharField(default='No', max_length=4)),
                ('active_back', models.CharField(default='No', max_length=4)),
                ('url', models.CharField(max_length=500)),
                ('company_id', models.IntegerField(default=-1)),
            ],
        ),
        migrations.CreateModel(
            name='Verify',
            fields=[
                ('v_id', models.AutoField(primary_key=True, serialize=False)),
                ('prn', models.CharField(max_length=50)),
            ],
        ),
    ]
