# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-05-09 13:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=60, unique=True)),
                ('password', models.CharField(max_length=12)),
                ('other_details', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('c_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('criteria', models.FloatField(blank=True, null=True)),
                ('back', models.CharField(blank=True, max_length=100, null=True)),
                ('position', models.CharField(blank=True, max_length=30, null=True)),
                ('salary', models.FloatField(blank=True, null=True)),
                ('ppt_date', models.DateTimeField(blank=True, null=True)),
                ('hired_count', models.IntegerField(blank=True, null=True)),
                ('other_details', models.CharField(blank=True, max_length=1000, null=True)),
                ('placed_url', models.CharField(blank=True, max_length=500, null=True)),
                ('reg_start', models.DateTimeField(blank=True, null=True)),
                ('reg_end', models.DateTimeField(blank=True, null=True)),
                ('reg_link', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('msg_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=200)),
                ('message', models.CharField(blank=True, default='', max_length=10000, null=True)),
                ('url', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('r_id', models.AutoField(primary_key=True, serialize=False)),
                ('shortlist', models.CharField(max_length=100)),
                ('filename', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=100)),
                ('other_details', models.CharField(max_length=1000)),
                ('c_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Company')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('s_id', models.AutoField(primary_key=True, serialize=False)),
                ('college_id', models.CharField(max_length=20, unique=True)),
                ('roll', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=60, unique=True)),
                ('password', models.CharField(max_length=12)),
                ('phone', models.CharField(max_length=10)),
                ('gender', models.CharField(max_length=10)),
                ('branch', models.CharField(max_length=6)),
                ('prn', models.CharField(max_length=20, unique=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('per_address', models.CharField(blank=True, max_length=1000, null=True)),
                ('cur_address', models.CharField(blank=True, max_length=1000, null=True)),
                ('city', models.CharField(blank=True, max_length=30, null=True)),
                ('aadhar_number', models.CharField(blank=True, max_length=20, null=True)),
                ('pan_number', models.CharField(blank=True, max_length=20, null=True)),
                ('passport_number', models.CharField(blank=True, max_length=50, null=True)),
                ('tenth_board', models.CharField(blank=True, max_length=20, null=True)),
                ('tenth_marks', models.FloatField(blank=True, null=True)),
                ('tenth_schoolname', models.CharField(blank=True, max_length=100, null=True)),
                ('tenth_city', models.CharField(blank=True, max_length=30, null=True)),
                ('tenth_yeargap', models.BooleanField(default=False)),
                ('tenth_yeargap_reason', models.CharField(blank=True, max_length=50, null=True)),
                ('is_diploma', models.BooleanField(default=False)),
                ('twelveth_board', models.CharField(blank=True, max_length=20, null=True)),
                ('twelveth_year', models.CharField(blank=True, max_length=20, null=True)),
                ('twelveth_marks', models.FloatField(blank=True, null=True)),
                ('twelveth_schoolname', models.CharField(blank=True, max_length=50, null=True)),
                ('twelveth_city', models.CharField(blank=True, max_length=50, null=True)),
                ('twelveth_yeargap', models.BooleanField(default=False)),
                ('twelveth_yeargap_reason', models.CharField(blank=True, max_length=50, null=True)),
                ('diploma_board', models.CharField(blank=True, max_length=30, null=True)),
                ('diploma_marks', models.FloatField(blank=True, null=True)),
                ('diploma_outof', models.FloatField(blank=True, null=True)),
                ('diploma_year', models.CharField(blank=True, max_length=20, null=True)),
                ('fe_marks', models.IntegerField(blank=True, null=True)),
                ('fe_outof', models.IntegerField(blank=True, null=True)),
                ('se_marks', models.IntegerField(blank=True, null=True)),
                ('se_outof', models.IntegerField(blank=True, null=True)),
                ('te_marks', models.IntegerField(blank=True, null=True)),
                ('te_outof', models.IntegerField(blank=True, null=True)),
                ('total_marks', models.IntegerField(blank=True, null=True)),
                ('total_outof', models.IntegerField(blank=True, null=True)),
                ('average', models.FloatField(blank=True, null=True)),
                ('be_yeargap', models.BooleanField(default=False)),
                ('active_back', models.IntegerField(default=0)),
                ('passive_back', models.BooleanField(default=False)),
                ('placed', models.BooleanField(default=False)),
                ('url', models.CharField(blank=True, max_length=500, null=True)),
                ('lock', models.BooleanField(default=False)),
                ('c_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Company')),
            ],
        ),
        migrations.CreateModel(
            name='Verify',
            fields=[
                ('v_id', models.AutoField(primary_key=True, serialize=False)),
                ('prn', models.CharField(max_length=50)),
                ('college_id', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('y_id', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.CharField(max_length=50, unique=True)),
                ('total', models.IntegerField()),
                ('comp', models.IntegerField()),
                ('it', models.IntegerField()),
                ('entc', models.IntegerField()),
                ('total_placed', models.IntegerField(blank=True, null=True)),
                ('comp_placed', models.IntegerField(blank=True, null=True)),
                ('it_placed', models.IntegerField(blank=True, null=True)),
                ('entc_placed', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='y_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Year'),
        ),
        migrations.AddField(
            model_name='company',
            name='applied_students',
            field=models.ManyToManyField(to='app.Student'),
        ),
        migrations.AddField(
            model_name='company',
            name='y_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Year'),
        ),
    ]
