# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-15 17:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='active_back',
            field=models.CharField(default='No', max_length=2),
        ),
        migrations.AlterField(
            model_name='student',
            name='branch',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='student',
            name='placed',
            field=models.CharField(default='No', max_length=2),
        ),
    ]
