# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-03 06:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='lock',
            field=models.BooleanField(default=False),
        ),
    ]
