# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-05-26 16:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='applied_students',
            field=models.ManyToManyField(blank=True, to='app.Student'),
        ),
        migrations.AlterField(
            model_name='student',
            name='prn',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
