# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-18 08:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Average',
            fields=[
                ('a_id', models.AutoField(primary_key=True, serialize=False)),
                ('above', models.BooleanField(max_length=40)),
                ('percent', models.IntegerField()),
            ],
        ),
    ]
