# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-11 14:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='hired_people',
            field=models.IntegerField(default=0),
        ),
    ]
