# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-03 19:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='year',
            field=models.CharField(default=1999, max_length=50),
            preserve_default=False,
        ),
    ]
