# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-29 07:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='reg_end_date',
            new_name='reg_end',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='reg_start_date',
            new_name='reg_start',
        ),
    ]
