# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-06 10:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_student_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='Year',
            fields=[
                ('y_id', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.CharField(max_length=50, unique=True)),
                ('comp', models.IntegerField()),
                ('it', models.IntegerField()),
                ('entc', models.IntegerField()),
                ('comp_placed', models.IntegerField(blank=True, null=True)),
                ('it_placed', models.IntegerField(blank=True, null=True)),
                ('entc_placed', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
