# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-08 12:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_student_lock'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='applied_companies',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
