# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-31 10:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_result'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='result',
            name='id',
        ),
        migrations.AddField(
            model_name='result',
            name='r_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
