# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-28 18:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20160918_2054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='apti_date',
        ),
        migrations.RemoveField(
            model_name='company',
            name='interview_date',
        ),
        migrations.AddField(
            model_name='company',
            name='reg_link',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
