# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-29 08:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20161229_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='salary',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
