# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-06-17 04:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20170526_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='important',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 17, 4, 13, 23, 576000, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
