# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-06-17 05:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20170617_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='c_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Company'),
        ),
    ]
