# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-03 05:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20161229_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='hsc',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='ssc',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
