# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-31 11:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20170131_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='placed_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
