# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-02-06 09:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='year',
            name='comp_placed',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='year',
            name='entc_placed',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='year',
            name='it_placed',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
