# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-09 09:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_student_applied_companies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='applied_companies',
        ),
        migrations.AddField(
            model_name='company',
            name='applied_students',
            field=models.ManyToManyField(to='app.Student'),
        ),
    ]
