# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-02-06 20:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20170206_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='url',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
