# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-06-17 19:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20170617_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='lock',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='company',
            name='status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
