# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-06-17 19:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20170618_0100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='c_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Company'),
        ),
    ]
