# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-02-07 18:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_message_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Average',
            fields=[
                ('a_id', models.AutoField(primary_key=True, serialize=False)),
                ('above', models.BooleanField(default=True)),
                ('percent', models.FloatField()),
            ],
        ),
        migrations.AlterField(
            model_name='message',
            name='message',
            field=models.CharField(blank=True, default='', max_length=10000, null=True),
        ),
    ]
