# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-03 16:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_student_roll'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='url',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
