# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-02-07 21:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20170208_0006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='average',
            name='above',
        ),
        migrations.RemoveField(
            model_name='average',
            name='percent',
        ),
        migrations.AddField(
            model_name='average',
            name='above_below',
            field=models.CharField(default='Above 65', max_length=40),
            preserve_default=False,
        ),
    ]
