# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-02-09 18:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20170208_0303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='average',
            name='above_below',
        ),
        migrations.AddField(
            model_name='average',
            name='above',
            field=models.BooleanField(default=65, max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='average',
            name='percent',
            field=models.IntegerField(default=65),
            preserve_default=False,
        ),
    ]
