# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-03 20:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20170104_0140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='hsc',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='ssc',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
