# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-03 20:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_student_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='college_id',
            field=models.CharField(max_length=50),
        ),
    ]
