# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-06-20 08:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20170618_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
    ]
