# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-06-24 06:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20170624_1131'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='me_firt_year_marks',
            new_name='me_fy_marks',
        ),
        migrations.AddField(
            model_name='student',
            name='me_sy_marks',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
