# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-06-24 11:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20170624_1235'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='criteria',
            new_name='be_criteria',
        ),
        migrations.AddField(
            model_name='company',
            name='me_criteria',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
