# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-06-26 04:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_auto_20170625_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='update_marks',
            field=models.BooleanField(default=False),
        ),
    ]
