# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-06-26 04:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_student_update_marks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='update_marks',
            field=models.IntegerField(default=0),
        ),
    ]
