# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-06-26 11:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_auto_20170626_0938'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='be_marks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='be_outof',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
