# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-06-29 07:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_auto_20170629_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='be_outof',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='fe_outof',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='se_outof',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='te_outof',
            field=models.IntegerField(),
        ),
    ]
