# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-06-29 07:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_auto_20170629_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='be_outof',
            field=models.IntegerField(default=750),
        ),
        migrations.AlterField(
            model_name='student',
            name='fe_outof',
            field=models.IntegerField(default=1400),
        ),
        migrations.AlterField(
            model_name='student',
            name='se_outof',
            field=models.IntegerField(default=1500),
        ),
        migrations.AlterField(
            model_name='student',
            name='te_outof',
            field=models.IntegerField(default=750),
        ),
    ]
