# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-06-29 08:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_auto_20170629_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='be_outof',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='te_outof',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
